### ISSUE TITLE
Interactivity problem with Leaflet in Chrome Canary

### ISSUE THREAD

**Issue by alperdincer** [cutting-room-floor/wax#242] opened 2012-07-24 12:35 UTC
Hi,

I'm using Chrome Canary (22.0.1215.1) for development and I released that wax and leaflet don't work together on this browser.

You can check documentation page (http://mapbox.com/wax/interaction-leaf.html) on Chrome Canary to see what's going on. 

Alper.

**Comment by tmcw** [comment] 2012-07-24 13:40
Can you see the problem in Chrome release cycle? This appears to work for me in Chrome Beta, and I'd rather not fix pre-release bugs in Chrome, of which there are many.

**Comment by alperdincer** [comment] 2012-07-24 13:45
There is no problem with Chrome Beta (version 21.0.1180.49 beta)

I just want to inform you about the issue.

Thanks a lot.

**Comment by tmcw** [comment] 2012-07-24 13:46
Thanks, hopefully Google catches it before it lands :)

**Comment by dooley** [comment] 2012-09-27 16:09
Unfortunatly not, Chrome Version 22.0.1229.79 (Win7) as well as latest stable version on Ubuntu has the problem from above. Any workaround?

**Comment by javierarce** [comment] 2012-09-28 08:13
Same thing in Chrome for mac. I'm currently using Chrome 22.0.1229.91 beta, but there are problems in the stable channel too.

**Comment by javisantana** [comment] 2012-09-28 09:51
the problem is with wax.offset, if you use $(el).offset return different values.

A quick fix (not tested in IE)

https://github.com/CartoDB/wax/commit/08b82471c1eee79349388b67978ac23282d6ec1b

**Comment by dooley** [comment] 2012-09-28 18:14
@ javisantana: Great, works without sideeffect in Chrome, Firefox, IE on Win7 (latest versions). Thanks for that!

**Comment by javisantana** [comment] 2012-09-28 18:21
@dooley thanks for testing.

also that fix solves some problems wax had with fixed positions on elements in the html page.

we have some testing for libraries that use wax, maybe is a good idea to "backport" them to wax to test this kind of things on different browser/OS/devices

**Comment by tmcw** [comment] 2012-10-01 14:04
@javisantana can you provide this as a pull request?

**Comment by javisantana** [comment] 2012-10-01 14:26
done

**Comment by tmcw** [comment] 2012-10-03 15:23
Pull request merged.

**Comment by miketahani** [comment] 2012-11-06 21:28
Fix worked for me, but it looks like the changes haven't made their way into dist/ on master. Thanks!

**Comment by javisantana** [comment] 2012-11-06 22:40
we have been using it extensively past months without any problem, i consider it fixed

**Comment by tmcw** [comment] 2012-11-06 22:52
Rebuilt and pushed in 1424765a8759fd76f7bb9388b430df4e082c2949

**Closed as completed** 2012-11-06 22:54 UTC
