### ISSUE TITLE
Tooltip.js - Active Popup doesn't stop new popups

### ISSUE THREAD

**Issue by robotastic** [cutting-room-floor/wax#99] opened 2011-08-23 15:35 UTC
If there is an active Popup up you can still click on a Interactivity point and have another popup appear above the active one. A tooltip doesn't appear when rolling over a point but you can still click and have multiple popups layered on top of each other... I am guessing this is not ideal. This even happens on the interactivity demo in the manual.

**Comment by tmcw** [comment] 2011-08-26 22:13
Yep, duplicate of #67.

**Closed as completed by tmcw** 2011-08-26 22:13 UTC
